version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t ./src
      - pip install --upgrade awscli

  pre_build:
    commands:
      - python -m unittest discover tests
  
  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
