version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
      - pip install -r src/equirements.txt -t ./src

  pre_build:
    commands:
      - python -m unittest discover src/tests
  
  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
