version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip awscli
      - pip install -r requirements.txt -t ./src
      - unzip output.zip -d ./src

  # pre_build:
  #   commands:
  #     - PYTHONPATH=$PYTHONPATH:./src python3.6 -m unittest discover tests
  
  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
